"""Ember (firebrand) spotting: lofting by the fire plume, transport by the wind.

Spotting is the mechanism by which a fire throws burning embers ahead of its
front; where they land in receptive fuel they start new fires, letting the fire
jump roads, rivers and slow-fuel barriers that a contiguous spread model (MTT)
cannot cross. FlamMap models it; pyflam's MTT did not — which is why pyflam fires
"choke" at fuel barriers and under-predict burn probability on landscapes where
FlamMap had spotting on.

Two models are provided.

:class:`SpottingModel` is a simple **parameterized** model: a deterministic
maximum reach from flame length and a lognormal landing draw, with fitted knobs
(``loft_coeff``, terminal velocity). It is fast and easy to calibrate.

:class:`FirebrandPhysics` is a **stochastic, physics-based** model where nothing
is a fitted reach: spotting *emerges* from the energy system and particle
mechanics, and the spatial distribution of landings is a Monte-Carlo result, not
an assumed shape. The chain per firebrand:

1. **Energy -> buoyant plume.** A cell's Byram fireline intensity ``I`` gives a
   convective heat-release rate ``Q_c = chi_c * I * L_front``; the buoyancy flux
   ``B = g Q_c / (rho cp T)`` sets the plume centre-line velocity
   ``w(z) = alpha (B/z)^(1/3)`` (Morton-Taylor-Turner plume theory).
2. **Particle mechanics.** Firebrand diameters are drawn from a size
   distribution; each gives a terminal velocity ``w_t`` from a drag balance and a
   combustion burnout time ``t_burn ~ d^2``.
3. **Lofting + transport.** A brand rises until the plume updraft drops to its
   ``w_t`` (loft height ``H = B (alpha/w_t)^3``), then descends while the wind
   advects it; the downwind reach is ``U H / w_t``. A brand whose flight time
   exceeds its burnout time lands as ash and cannot ignite.
4. **Ignition.** A still-burning brand ignites the receiving fuel with a
   probability that falls with the dead fuel moisture of that cell.

The randomness — number of brands (Poisson in intensity), sizes (lognormal),
direction (turbulent scatter), ignition (Bernoulli on a physical probability) —
makes the landing pattern and spot rate genuinely stochastic. The constants
(convective fraction, plume coefficient, char density, drag, a combustion rate)
are physical quantities with literature ranges, not reach calibrations.

References:
    Albini, F.A. 1979. Spot fire distance from burning trees -- a predictive
        model. USDA Forest Service GTR INT-56.
    Albini, F.A. 1983. Potential spotting distance from wind-driven surface
        fires. USDA Forest Service Research Paper INT-309.
    Morton, B.R.; Taylor, G.; Turner, J.S. 1956. Turbulent gravitational
        convection from maintained and instantaneous sources. Proc. R. Soc. A 234.
    Sardoy, N. et al. 2008. Numerical study of ground-level distribution of
        firebrands generated by line fires. Combustion and Flame 154.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

from .units import ft_to_m, ft_per_min_to_m_per_s, m_to_ft

# Byram fireline intensity: Btu/ft/s -> kW/m (convective plume is driven in SI).
_BTU_FT_S_TO_KW_M = 3.46414
_G = 9.81                # gravity, m/s^2
_RHO_AIR = 1.2           # kg/m^3
_CP_AIR = 1005.0         # J/kg/K
_T_AIR = 300.0           # K


def byram_flame_length(fireline_intensity) -> np.ndarray:
    """Byram flame length (ft) from fireline intensity (Btu/ft/s)."""
    i = np.asarray(fireline_intensity, dtype=float)
    return np.where(i > 0.0, 0.45 * np.power(np.maximum(i, 0.0), 0.46), 0.0)


@dataclass
class SpottingModel:
    """Parameters for the firebrand loft-and-drift spotting model.

    All lengths in ft, speeds in ft/min (pyflam's native units).

    Parameters
    ----------
    spot_probability:
        Probability that a given launch opportunity yields a firebrand that
        survives transport and ignites a new fire (FlamMap's spot probability).
    loft_coeff:
        Plume loft height as a multiple of flame length (``H = loft_coeff * L``).
    terminal_velocity:
        Firebrand terminal/settling velocity (ft/min); smaller -> longer flights.
    median_fraction:
        Median landing distance as a fraction of ``D_max`` (lognormal median).
    distance_sigma:
        Lognormal shape (sigma of ln distance); larger -> heavier long tail.
    direction_sigma_deg:
        Std-dev of the landing direction about straight downwind (degrees).
    min_intensity:
        Below this fireline intensity (Btu/ft/s) a cell launches no embers.
    spot_delay:
        Minutes between landing and the spot fire becoming an active ignition
        (FlamMap's spot delay).
    launch_fraction:
        Fraction of burning cells considered as launch opportunities per fire
        (subsampling of the front, keeps the cost bounded on huge fires).
    """

    spot_probability: float = 0.1
    loft_coeff: float = 12.0
    terminal_velocity: float = 250.0      # ~1.3 m/s
    median_fraction: float = 0.5
    distance_sigma: float = 0.6
    direction_sigma_deg: float = 20.0
    min_intensity: float = 10.0
    spot_delay: float = 2.0               # minutes (FlamMap default 120 s)
    launch_fraction: float = 0.02

    def max_spot_distance(self, fireline_intensity, wind_20ft):
        """Maximum downwind spotting distance (ft): ``(U/w_t) * loft_coeff * L``."""
        L = byram_flame_length(fireline_intensity)
        H = self.loft_coeff * L
        u = np.asarray(wind_20ft, dtype=float)
        return (u / self.terminal_velocity) * H

    def generate_spots(self, field, arrival_time, *, wind_20ft, wind_direction,
                       max_time, rng, fuel_moisture=None):
        """Polymorphic spot generator (see :func:`generate_spot_ignitions`)."""
        return generate_spot_ignitions(
            field, arrival_time, wind_20ft=wind_20ft,
            wind_direction=wind_direction, max_time=max_time, model=self, rng=rng)


def generate_spot_ignitions(
    field,
    arrival_time: np.ndarray,
    *,
    wind_20ft: float,
    wind_direction: float,
    max_time: float,
    model: SpottingModel,
    rng: np.random.Generator,
    already_burned: np.ndarray | None = None,
) -> list[tuple[int, int, float]]:
    """Launch embers from a burning fire and return new spot ignitions.

    Considers cells reached by ``arrival_time`` (<= ``max_time``) as the fire,
    subsamples launch opportunities (``launch_fraction``), and for each that
    clears ``spot_probability`` and ``min_intensity`` lofts an ember downwind. An
    ember that lands in burnable, not-yet-burned fuel before ``max_time`` becomes
    a new ignition ``(row, col, ignition_time)`` with
    ``ignition_time = source_arrival + spot_delay``.
    """
    fli = field.fireline_intensity
    if fli is None:
        raise ValueError("spread field has no fireline_intensity; rebuild it")
    nrows, ncols = field.shape
    burnable = field.ros_max > 0.0
    burned = np.isfinite(arrival_time) & (arrival_time <= max_time)
    if already_burned is not None:
        burned = burned & ~already_burned   # only newly burned cells launch

    rr, cc = np.where(burned)
    if rr.size == 0:
        return []

    # Subsample launch opportunities, then keep those that spot successfully.
    k = max(1, int(rr.size * model.launch_fraction))
    pick = rng.choice(rr.size, size=min(k, rr.size), replace=False)
    rr, cc = rr[pick], cc[pick]
    src_i = fli[rr, cc]
    succeed = (src_i >= model.min_intensity) & (
        rng.random(rr.size) < model.spot_probability)
    rr, cc, src_i = rr[succeed], cc[succeed], src_i[succeed]
    if rr.size == 0:
        return []

    wind_toward = math.radians((wind_direction + 180.0) % 360.0)
    d_max = model.max_spot_distance(src_i, wind_20ft)               # ft
    # Lognormal landing distance, median = median_fraction * D_max, capped.
    z = rng.normal(0.0, model.distance_sigma, size=rr.size)
    dist = np.minimum(model.median_fraction * d_max * np.exp(z), d_max)
    bearing = wind_toward + np.radians(
        rng.normal(0.0, model.direction_sigma_deg, size=rr.size))

    # Landing cell: east = +col, north = -row.
    dx = dist * np.sin(bearing)
    dy = dist * np.cos(bearing)
    land_r = (rr - np.round(dy / field.cellsize_y)).astype(int)
    land_c = (cc + np.round(dx / field.cellsize_x)).astype(int)
    t_ig = arrival_time[rr, cc] + model.spot_delay

    spots: list[tuple[int, int, float]] = []
    for lr, lc, ti in zip(land_r.tolist(), land_c.tolist(), t_ig.tolist()):
        if 0 <= lr < nrows and 0 <= lc < ncols and burnable[lr, lc] \
                and ti < max_time and not burned[lr, lc]:
            spots.append((lr, lc, ti))
    return spots


# --- Measured firebrand (per-ember) data, for the particle sub-models ---------
# d^2-law char burning constant K (m^2/s): d^2(t) = d0^2 - K t, so burnout time
# = d0^2 / K. Tarifa et al. (1965, 1967) measured K ~ 2.5e-7..8e-7 for wood;
# the default uses the mid-range. ``combustion_rate = 1 / K``.
TARIFA_BURN_CONSTANT = 5.0e-7
TARIFA_BURN_CONSTANT_RANGE = (2.5e-7, 8.0e-7)

# Measured firebrand terminal/settling velocities, (diameter_mm, w_t_m_per_s),
# for validating the drag sub-model. Magnitudes after Tohidi & Kaye (2017) and
# Manzello et al. firebrand-collection experiments: mm-cm woody brands settle at
# ~2-7 m/s.
FIREBRAND_TERMINAL_VELOCITY_DATA = [
    (2.0, 2.3), (5.0, 3.7), (10.0, 5.2), (20.0, 7.4),
]

# Order-of-magnitude maximum spotting distances from the spotting literature,
# used to calibrate the one weakly-constrained physical length (``front_length``).
# Each entry: (fireline_intensity_kW_per_m, wind_20ft_m_per_s, max_distance_m).
# Sources: Albini (1979, 1983); Koo, E. et al. 2010, "Firebrands and spotting
# ignition in large-scale fires", Int. J. Wildland Fire 19; Sardoy et al. (2008).
# These are consensus magnitudes, not a single experiment — replace with your own
# measured (intensity, wind, distance) rows via :func:`calibrate_front_length`.
LITERATURE_SPOT_ANCHORS = [
    (100.0, 5.0, 100.0),     # low-intensity surface fire
    (1000.0, 8.0, 500.0),    # shrub / moderate
    (5000.0, 10.0, 1500.0),  # high-intensity timber
    (30000.0, 15.0, 3000.0),  # crown / extreme
]


@dataclass
class FirebrandPhysics:
    """Stochastic, physics-based firebrand spotting model.

    Spotting distance is not a calibrated parameter here: it emerges from the
    fire's convective energy (buoyant-plume loft) and each firebrand's mechanics
    (size -> terminal velocity, drag, combustion burnout). See the module
    docstring for the chain. The constants below are physical quantities with
    literature ranges; the model is stochastic, so repeated runs differ and the
    landing distribution is a Monte-Carlo outcome rather than an assumed shape.

    Parameters (SI unless noted)
    ----------------------------
    convective_fraction:
        Fraction of heat release that is convective and drives the plume (~0.7).
    front_length:
        Coherent flaming-front length feeding one plume element (m). Sets the
        per-source heat release with the per-length fireline intensity; a
        physical length scale, resolution-independent (unlike the cell size).
    plume_coefficient:
        Centre-line plume-velocity constant ``alpha`` in ``w = alpha (B/z)^1/3``
        (Morton-Taylor-Turner, ~1.9).
    firebrand_density:
        Char/ember bulk density (kg/m^3, ~300).
    drag_coefficient:
        Firebrand drag coefficient for the terminal-velocity balance (~1.2).
    size_median, size_sigma:
        Lognormal firebrand diameter distribution: median (m) and shape.
    combustion_rate:
        Burnout-time constant ``t_burn = combustion_rate * d^2`` (s/m^2); a
        diameter-squared (diffusion-limited) char burnout law.
    embers_per_source:
        Mean number of firebrands launched per launch opportunity at the
        reference intensity (Poisson mean scales with intensity).
    reference_intensity:
        Fireline intensity (kW/m) at which ``embers_per_source`` applies.
    min_intensity:
        Below this fireline intensity (kW/m) a cell launches no firebrands.
    ignition_moisture_scale:
        Dead fuel moisture (fraction) at which the landing-ignition probability
        falls to ``1/e``; higher fuel moisture -> fewer successful ignitions.
    direction_sigma_deg:
        Turbulent scatter of the launch bearing about downwind (degrees).
    spot_delay:
        Minutes between landing and the spot fire becoming an active ignition.
    launch_fraction:
        Fraction of burning cells sampled as launch opportunities per fire.
    """

    convective_fraction: float = 0.7
    front_length: float = 100.0     # calibrated to LITERATURE_SPOT_ANCHORS (p98)
                                    # with the refined Manzello/Tarifa particle physics
    plume_coefficient: float = 1.9
    firebrand_density: float = 300.0
    drag_coefficient: float = 1.2
    size_median: float = 0.004          # 4 mm (Manzello firebrand experiments)
    size_sigma: float = 0.55
    combustion_rate: float = 1.0 / TARIFA_BURN_CONSTANT  # Tarifa d^2-law (=2e6)
    embers_per_source: float = 3.0
    reference_intensity: float = 500.0  # kW/m
    min_intensity: float = 50.0         # kW/m
    ignition_moisture_scale: float = 0.12
    direction_sigma_deg: float = 18.0
    spot_delay: float = 2.0
    launch_fraction: float = 0.05

    # --- physical sub-models (all SI) -------------------------------------
    def terminal_velocity(self, diameter_m):
        """Firebrand terminal velocity (m/s) from a drag balance."""
        d = np.asarray(diameter_m, dtype=float)
        return np.sqrt((4.0 / 3.0) * (self.firebrand_density / _RHO_AIR)
                       * _G * d / self.drag_coefficient)

    def buoyancy_flux(self, intensity_kw_m):
        """Plume buoyancy flux B (m^4/s^3) from fireline intensity (kW/m)."""
        q_c = self.convective_fraction * np.asarray(intensity_kw_m, float) \
            * 1000.0 * self.front_length                      # W per source
        return _G * q_c / (_RHO_AIR * _CP_AIR * _T_AIR)

    def loft_height(self, intensity_kw_m, terminal_velocity):
        """Loft height (m): where plume updraft drops to the brand's w_t."""
        b = self.buoyancy_flux(intensity_kw_m)
        wt = np.asarray(terminal_velocity, dtype=float)
        return b * (self.plume_coefficient / wt) ** 3

    def burnout_time(self, diameter_m):
        """Firebrand burnout time (s) from the d^2-law: ``d^2 / K`` (Tarifa)."""
        d = np.asarray(diameter_m, dtype=float)
        return self.combustion_rate * d * d

    @property
    def burning_constant(self) -> float:
        """The d^2-law char burning constant ``K = 1 / combustion_rate`` (m^2/s)."""
        return 1.0 / self.combustion_rate

    @classmethod
    def from_burning_constant(cls, k_m2_per_s: float, **kwargs):
        """Build a model from a measured d^2-law burning constant ``K`` (m^2/s)."""
        return cls(combustion_rate=1.0 / k_m2_per_s, **kwargs)

    def ignition_probability(self, dead_fuel_moisture):
        """Probability a landed, burning brand ignites the receiving fuel."""
        m = np.asarray(dead_fuel_moisture, dtype=float)
        return np.exp(-m / self.ignition_moisture_scale)

    def spot_distance_distribution(self, intensity_kw_m, wind_ms, *,
                                   n: int = 20000, rng=None):
        """Landing distances (m) of surviving firebrands from one source.

        Samples ``n`` firebrands, propagates each through loft + transport +
        burnout, and returns the downwind landing distances of those that reach
        the ground still burning. This isolates the firebrand-transport physics
        for comparison against measured spot-distance data (no fire grid).
        """
        if rng is None:
            rng = np.random.default_rng()
        d = rng.lognormal(np.log(self.size_median), self.size_sigma, size=n)
        wt = self.terminal_velocity(d)
        H = self.loft_height(intensity_kw_m, wt)
        t_flight = H / wt
        survives = t_flight <= self.burnout_time(d)
        reach = np.asarray(wind_ms, float) * H / wt
        return reach[survives]

    # --- spot generation ---------------------------------------------------
    def generate_spots(self, field, arrival_time, *, wind_20ft, wind_direction,
                       max_time, rng, fuel_moisture=None):
        """Launch firebrands from the fire and return ignited spot fires.

        ``wind_20ft`` in ft/min, ``wind_direction`` deg FROM, ``fuel_moisture``
        the dead 1-h moisture (fraction) of the receiving fuel (scalar or array;
        controls landing ignition). Returns ``(row, col, ignition_time)`` list.
        """
        fli = field.fireline_intensity
        if fli is None:
            raise ValueError("spread field has no fireline_intensity; rebuild it")
        nrows, ncols = field.shape
        burnable = field.ros_max > 0.0
        burned = np.isfinite(arrival_time) & (arrival_time <= max_time)
        rr, cc = np.where(burned)
        if rr.size == 0:
            return []

        # Sample launch opportunities; each launches Poisson(mean ~ intensity)
        # firebrands, so more energetic fires throw more brands.
        k = max(1, int(rr.size * self.launch_fraction))
        pick = rng.choice(rr.size, size=min(k, rr.size), replace=False)
        rr, cc = rr[pick], cc[pick]
        intensity_kw = fli[rr, cc] * _BTU_FT_S_TO_KW_M           # kW/m
        active = intensity_kw >= self.min_intensity
        rr, cc, intensity_kw = rr[active], cc[active], intensity_kw[active]
        if rr.size == 0:
            return []

        lam = self.embers_per_source * (intensity_kw / self.reference_intensity)
        n_brands = rng.poisson(np.clip(lam, 0.0, 50.0))
        total = int(n_brands.sum())
        if total == 0:
            return []
        # Expand each source to its brands.
        src = np.repeat(np.arange(rr.size), n_brands)
        i_kw = intensity_kw[src]
        src_r, src_c = rr[src], cc[src]

        # Particle mechanics -> loft -> flight; drop brands that burn out aloft.
        d = rng.lognormal(np.log(self.size_median), self.size_sigma, size=total)
        wt = self.terminal_velocity(d)                          # m/s
        H = self.loft_height(i_kw, wt)                          # m
        t_flight = H / wt                                       # s (descent)
        survives = t_flight <= self.burnout_time(d)

        u = ft_per_min_to_m_per_s(np.asarray(wind_20ft, float))  # m/s
        reach_m = u * H / wt                                    # downwind drift (m)
        wind_toward = math.radians((wind_direction + 180.0) % 360.0)
        bearing = wind_toward + np.radians(
            rng.normal(0.0, self.direction_sigma_deg, size=total))

        reach_ft = m_to_ft(reach_m)
        dx = reach_ft * np.sin(bearing)
        dy = reach_ft * np.cos(bearing)
        land_r = (src_r - np.round(dy / field.cellsize_y)).astype(int)
        land_c = (src_c + np.round(dx / field.cellsize_x)).astype(int)
        t_ig = arrival_time[src_r, src_c] + self.spot_delay

        spots: list[tuple[int, int, float]] = []
        in_bounds = survives & (land_r >= 0) & (land_r < nrows) \
            & (land_c >= 0) & (land_c < ncols) & (t_ig < max_time)
        idx = np.where(in_bounds)[0]
        for j in idx:
            lr, lc = int(land_r[j]), int(land_c[j])
            if not burnable[lr, lc] or burned[lr, lc]:
                continue
            # Physical ignition probability from the receiving fuel's moisture.
            m_here = (fuel_moisture[lr, lc] if isinstance(fuel_moisture, np.ndarray)
                      else (fuel_moisture if fuel_moisture is not None else 0.0))
            if rng.random() < float(self.ignition_probability(m_here)):
                spots.append((lr, lc, float(t_ig[j])))
        return spots


def calibrate_front_length(
    anchors=LITERATURE_SPOT_ANCHORS,
    *,
    base: "FirebrandPhysics | None" = None,
    percentile: float = 95.0,
    iterations: int = 8,
    rng=None,
):
    """Fit ``front_length`` so modelled spot distances match measured anchors.

    ``anchors`` is an iterable of ``(fireline_intensity_kW_m, wind_20ft_m_s,
    distance_m)`` rows (defaults to :data:`LITERATURE_SPOT_ANCHORS`; pass your own
    measured maxima to recalibrate). Landing distance is roughly linear in
    ``front_length``, so each step scales it by the geometric mean of (observed /
    modelled) distance at ``percentile``. It is only *roughly* linear — a longer
    loft also lengthens the flight, so more far brands burn out (a self-limiting
    effect) — so the fit is **iterated** to a fixed point. Returns the fitted
    ``front_length`` (m).
    """
    import copy
    if rng is None:
        rng = np.random.default_rng(0)
    model = copy.copy(base or FirebrandPhysics())
    for _ in range(iterations):
        log_ratios = []
        for intensity, wind_ms, observed in anchors:
            d = model.spot_distance_distribution(intensity, wind_ms, rng=rng)
            if d.size == 0:
                continue
            modelled = float(np.percentile(d, percentile))
            if modelled > 0.0:
                log_ratios.append(math.log(observed / modelled))
        if not log_ratios:
            break
        step = math.exp(sum(log_ratios) / len(log_ratios))
        model.front_length *= step
        if abs(math.log(step)) < 0.02:        # converged within ~2%
            break
    return model.front_length


def spot_distance_report(model=None, anchors=LITERATURE_SPOT_ANCHORS, *,
                         percentile: float = 95.0, rng=None):
    """Modelled vs measured spot distance at each anchor (for validation).

    Returns a list of dicts with the scenario, the modelled distance at
    ``percentile``, the measured distance, and their ratio.
    """
    if rng is None:
        rng = np.random.default_rng(0)
    model = model or FirebrandPhysics()
    out = []
    for intensity, wind_ms, observed in anchors:
        d = model.spot_distance_distribution(intensity, wind_ms, rng=rng)
        modelled = float(np.percentile(d, percentile)) if d.size else 0.0
        out.append({
            "intensity_kw_m": intensity, "wind_ms": wind_ms,
            "modelled_m": modelled, "measured_m": observed,
            "ratio": modelled / observed if observed else float("nan"),
        })
    return out


def calibrate_burnout(measurements):
    """Fit the d^2-law burning constant ``K`` (m^2/s) from measured firebrands.

    ``measurements`` is an iterable of ``(diameter_m, burnout_time_s)`` rows
    (e.g. Tarifa-style firebrand combustion data). Since ``t_burn = d^2 / K``,
    the least-squares ``K`` is the mean of ``d^2 / t``. Build a model with
    ``FirebrandPhysics.from_burning_constant(K)``.
    """
    ks = [d * d / t for d, t in measurements if t > 0.0]
    if not ks:
        return TARIFA_BURN_CONSTANT
    return float(np.mean(ks))
